MTDSA-11611: Add messages and metadata case classes for v3 calc retri…
hmrc/individual-calculations-api pull request #316
Opened 2022-04-07 08:48 UTC by BetaDraconis

…eval.

2022-04-12 11:07 UTC, vfryer12 commented on test/v2/connectors/CrystallisationConnectorSpec.scala
> +import v2.models.response.common.DesUnit
The DesUnit import in the V2 Spec endpoints is not working, it has not been updated to DesUnit in v2. I believe it's still DownstreamUnit

2022-04-12 11:12 UTC, vfryer12 commented on test/v2/connectors/CrystallisationConnectorSpec.scala
> +import v2.models.response.common.DesUnit
I think due to a shuffle around with the layout a couple of imports are no longer pointing to the correct locations

TaxRateSpec models response import needs to be updated to `import v3.models.response.common.TaxRate._`

Base connectorSpec you have `import v3.models.response.common.DownstreamResponse` and DownstreamResponse is not located here so it’s not recognising DownstreamResponse

2022-04-14 10:19 UTC, Mbrookesy requested changes

2022-04-14 10:19 UTC, Mbrookesy commented on resources/public/api/conf/3.0/application.raml
> +          get: !include endpoints/retrieve.raml
It seems the commit for the scaffolding RAML got included in this PR

2022-04-14 10:25 UTC, Mbrookesy requested changes

2022-04-14 10:25 UTC, Mbrookesy commented on app/v3/models/response/retrieveCalculation/messages/Messages.scala
> +
The `message` field should be `text`

2022-04-14 10:39 UTC, BetaDraconis commented on app/v3/models/response/common/CalculationType.scala
> +    case "POA" => `POA`
I'm waiting to see what the results of our outstanding questions on this field are before making any changes.

2022-04-14 10:45 UTC, merged