[MTDSA-11680] - Submit a Self Assessment Final Declaration Connector and Service
hmrc/individual-calculations-api pull request #335
Opened 2022-04-19 08:25 UTC by DreamcastKnight

2022-04-22 13:43 UTC, james-work-account approved these changes

2022-04-22 15:07 UTC, james-work-account requested changes

2022-04-22 15:07 UTC, james-work-account commented on app/v3/connectors/SubmitFinalDeclarationConnector.scala
> +    val taxYear: TaxYear      = request.taxYear
```suggestion
    val taxYear: String      = request.taxYear.toDownstream
```

2022-04-22 15:07 UTC, james-work-account commented on test/v3/connectors/SubmitFinalDeclarationConnectorSpec.scala
> +          requiredHeaders = requiredDownstreamHeadersPost,
```suggestion
          url = s"$baseUrl/income-tax/calculation/nino/$nino/${taxYear.toDownstream}/$calculationId/crystallise",
          config = dummyDesHeaderCarrierConfig,
          body = EmptyJsonBody,
          requiredHeaders = requiredDesHeadersPost,
```

2022-04-22 15:07 UTC, james-work-account commented on test/v3/services/SubmitFinalDeclarationServiceSpec.scala
> +    val taxYear: String       = "2019-20"
```suggestion
    val taxYear: TaxYear       = TaxYear("2019-20")  
```

2022-04-22 15:07 UTC, james-work-account commented on test/v3/services/SubmitFinalDeclarationServiceSpec.scala
> +        }
```suggestion
      def serviceError(downstreamErrorCode: String, error: MtdError): Unit =
        s"a $downstreamErrorCode error is returned from the service" in new Test {

          MockSubmitFinalDeclarationConnector
            .submitFinalDeclaration(request)
            .returns(Future.successful(
              Left(ResponseWrapper(
                correlationId,
                DesErrors.single(DesErrorCode(downstreamErrorCode))))))

          await(service.submitFinalDeclaration(request)) shouldBe Left(ErrorWrapper(correlationId, error))
        }
```

This is still written like v2 calc - update to look more like Trigger

2022-04-22 15:07 UTC, james-work-account commented on test/v3/services/SubmitFinalDeclarationServiceSpec.scala
> +        ("SERVICE_UNAVAILABLE", DownstreamError, SERVICE_UNAVAILABLE)
```suggestion
        ("INVALID_IDTYPE", DownstreamError),
        ("INVALID_IDVALUE", NinoFormatError),
        ("INVALID_TAXYEAR", TaxYearFormatError),
        ("INVALID_CALCID", CalculationIdFormatError),
        ("NOT_FOUND", NotFoundError),
        ("INCOME_SOURCES_CHANGED", RuleIncomeSourcesChangedError),
        ("RECENT_SUBMISSIONS_EXIST", RuleRecentSubmissionsExistError),
        ("RESIDENCY_CHANGED", RuleResidencyChangedError),
        ("INVALID_INCOME_SOURCES", RuleIncomeSourcesInvalid),
        ("INCOME_SUBMISSIONS_NOT_EXIST", RuleNoIncomeSubmissionsExistError),
        ("BUSINESS_VALIDATION", RuleSubmissionFailed),
        ("FINAL_DECLARATION_RECEIVED", RuleFinalDeclarationReceivedError),
        ("SERVER_ERROR", DownstreamError),
        ("SERVICE_UNAVAILABLE", DownstreamError)
```

2022-04-25 08:27 UTC, jeremystone commented on test/v3/connectors/SubmitFinalDeclarationConnectorSpec.scala
> +      implicit val hc: HeaderCarrier = HeaderCarrier(otherHeaders = otherHeaders ++ Seq("Content-Type" -> "application/json"))
Please remove this line: the connector should send the correct `Content-Type` independently of any `Content-Type` in the request that we received. (The test does pass without it.)
```suggestion
```

2022-04-25 08:27 UTC, jeremystone commented on test/v3/connectors/SubmitFinalDeclarationConnectorSpec.scala
> +  val taxYear: TaxYear        =  TaxYear("2021-22")
```suggestion
  val taxYear: TaxYear        =  TaxYear.fromMtd("2021-22")
```
The test only works as is because it replicates what the connector code does and calls `taxYear.toDownstream` - both will evaluate to "2021-22" which is the MTD format.

2022-04-25 08:27 UTC, jeremystone commented on test/v3/connectors/SubmitFinalDeclarationConnectorSpec.scala
> +          url = s"$baseUrl/income-tax/calculation/nino/$nino/${taxYear.toDownstream}/$calculationId/crystallise",
Maybe replace `taxYear.toDownstream` with `2022` (or declare a `val downstreamTaxYear = "2022"` at the top and use here) for a stronger test.

2022-04-25 09:08 UTC, HarryBaxter reviewed
Misclicked approval on this PR

2022-04-25 10:57 UTC, merged