MTDSA-14925: Added logic for R8B changes
hmrc/individual-calculations-api pull request #423
Opened 2023-03-02 18:34 UTC by narendravijayarao

2023-03-03 10:26 UTC, tom-lloyd-hmrc commented on app/v3/controllers/RetrieveCalculationController.scala
> +              response.calculation.exists(calc => calc.endOfYearEstimate.exists(eoy => eoy.totalAllowancesAndDeductions.isDefined))) {
I think Chandra's doing the main review, but just noticed here we could probably simplify this code a little by calculating the response first, and then creating the hateoas data once afterwards.

2023-03-03 11:52 UTC, narendravijayarao commented on app/v3/controllers/RetrieveCalculationController.scala
> +              response.calculation.exists(calc => calc.endOfYearEstimate.exists(eoy => eoy.totalAllowancesAndDeductions.isDefined))) {
Doesn't make any difference, we will have an extra **_val response_**. Also, I don't want to disturb the existing code much. This release is in April. Just in 1 month we may remove this feature switch completely

2023-03-03 12:01 UTC, sudoku007 requested changes

2023-03-03 12:06 UTC, sudoku007 commented on app/v3/controllers/RetrieveCalculationController.scala
> +              response.calculation.exists(calc => calc.endOfYearEstimate.exists(eoy => eoy.totalAllowancesAndDeductions.isDefined))) {
Yeah I agree we could simplify it a bit by adding a wrapper method to adapt the response based on the feature switch flag,  we could then unit test that method independently too.

2023-03-03 12:15 UTC, narendravijayarao commented on test/v3/controllers/RetrieveCalculationControllerSpec.scala
> +
The first test **"happy path with r8b-api disabled"** is checking this scenario

2023-03-03 12:29 UTC, sudoku007 commented on test/v3/controllers/RetrieveCalculationControllerSpec.scala
> +
yeah, missed seeing this

2023-03-06 11:37 UTC, sudoku007 approved these changes

2023-03-06 11:40 UTC, merged