MTDSA-18817: Create V4 for SubmitFinalDeclaration API & Added testcase
hmrc/individual-calculations-api pull request #470
Opened 2023-08-25 09:47 UTC by chetan-jain-atos

2023-08-30 10:59 UTC, KobithasanVasantharajah requested changes

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on app/v3/controllers/SubmitFinalDeclarationController.scala
> +        if (retry <= 3) {
Can we make the 3 into a variable? MAX_NRS_RETRIES which can be stored in application.conf. Note this will also need to be added to app-config-base, app-config-externaltest, app-config-production.

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on app/v3/controllers/SubmitFinalDeclarationController.scala
> +        if (retry <= 3) {
```suggestion
        if (retry > 3) {
``` 
We need to update this because the retry will never be triggered otherwise

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on app/v3/controllers/SubmitFinalDeclarationController.scala
> +          Thread.sleep(100)
Rather than using a 100 milliseconds we should use exponential backoff. 
```suggestion
          Thread.sleep(interval * 2^retry)
```
Where a suitable interval is to be decided i.e. 1 second is reasonable

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on app/v4/controllers/SubmitFinalDeclarationController.scala
> +        if (retry <= 3) {
All the comments from v3 apply here too.

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on app/v3/models/request/submitFinalDeclaration.scala
> +  def toNrsJson: JsValue = Json.obj("calculationId" -> calculationId.calculationId)
We should change this to:
```suggestion
  def toNrsJson: JsValue = Json.obj("calculationId" -> s"calculationId")
```

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on app/v4/models/request/submitFinalDeclaration.scala
> +  def toNrsJson: JsValue = Json.obj("calculationId" -> calculationId.calculationId)
We should change this to:
```suggestion
  def toNrsJson: JsValue = Json.obj("calculationId" -> s"calculationId")
```

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on app/v4/connectors/SubmitFinalDeclarationConnector.scala
> +    import api.connectors.httpparsers.StandardDownstreamHttpParser._
Can we move this import to the top of the file with the other imports? Can we also update v3 with this change too?

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on test/v3/controllers/SubmitFinalDeclarationControllerSpec.scala
> +  "V3-submit final declaration" should {
We don't need to specify v3 as this is a v3 spec. We should also use the name of the controller for example, 
```suggestion
  "SubmitFinalDeclarationController" should {
```

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on test/v3/services/SubmitFinalDeclarationServiceSpec.scala
> +      CalculationId(calculationId)
We should update this to follow the same format as nino and taxYear i.e: `val calculationId: CalculationId = CalculationId("a1e8057e-fbbc-47a8-a8b4-78d9f015c253")`

```suggestion
      calculationId
```

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on test/v3/connectors/SubmitFinalDeclarationConnectorSpec.scala
> +    CalculationId(calculationId)
We should update Nino and CalculationID to follow the same format as taxYear and taxYear i.e: `val calculationId: CalculationId = CalculationId("a1e8057e-fbbc-47a8-a8b4-78d9f015c253")`

```suggestion
      calculationId
```

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on test/v4/controllers/SubmitFinalDeclarationControllerSpec.scala
> +  "V4-submit final declaration" should {
We don't need to specify v4 as its a v4 spec. We should also update with 
```suggestion
  "SubmitFinalDeclarationController" should {
```

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on test/v3/controllers/SubmitFinalDeclarationControllerSpec.scala
> +        // fallback to just logging the calculationId:
This comment can be removed.

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on test/v4/controllers/SubmitFinalDeclarationControllerSpec.scala
> +        // fallback to just logging the calculationId:
This comment can be removed.

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on test/v3/services/RetrieveCalculationServiceSpec.scala
>    private val taxYear       = "2019-20"
```suggestion
  private val taxYear : TaxYear      = TaxYear.fromMtd("2019-20")
```

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on test/v3/services/RetrieveCalculationServiceSpec.scala
>    private val calculationId = "someCalcId"
```suggestion
  private val calculationId: CalculationId = CalculationId("someCalcId")
```

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on test/v4/services/SubmitFinalDeclarationServiceSpec.scala
> +      val errors = Seq(
```suggestion
      val errors = List(
```

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on test/v4/services/SubmitFinalDeclarationServiceSpec.scala
> +    val calculationId: String = "a1e8057e-fbbc-47a8-a8b4-78d9f015c253"
```suggestion
    val calculationId: CalculationId = CalculationId("a1e8057e-fbbc-47a8-a8b4-78d9f015c253")
```

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on test/v4/services/SubmitFinalDeclarationServiceSpec.scala
> +      CalculationId(calculationId)
```suggestion
      calculationId
```

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on test/v3/services/RetrieveCalculationServiceSpec.scala
> +  val request: RetrieveCalculationRequest   = RetrieveCalculationRequest(nino, TaxYear.fromMtd(taxYear), CalculationId(calculationId))
```suggestion
  val request: RetrieveCalculationRequest   = RetrieveCalculationRequest(nino, taxYear, calculationId))
```

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on test/v4/connectors/SubmitFinalDeclarationConnectorSpec.scala
> +  val nino: String          = "AA111111A"
```suggestion
  val nino: Nino          = Nino("AA111111A")
```

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on test/v4/connectors/SubmitFinalDeclarationConnectorSpec.scala
> +  val calculationId: String = "4557ecb5-fd32-48cc-81f5-e6acd1099f3c"
```suggestion
  val calculationId: CalculationId = CalculationId("4557ecb5-fd32-48cc-81f5-e6acd1099f3c")
```

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on test/v3/controllers/SubmitFinalDeclarationControllerSpec.scala
>    private val taxYear       = "2020-21"
Can we do this for all the files for nino, taxYear and calculationId?
```suggestion
  private val taxYear: TaxYear = TaxYear.fromMtd("2019-20")
```

2023-08-30 10:59 UTC, KobithasanVasantharajah commented on app/v4/services/SubmitFinalDeclarationService.scala
> +      "INVALID_CORRELATION_ID"         -> models.errors.InternalError,
Can we update the map without the models.error path for all the errors? 
```suggestion
      "INVALID_CORRELATION_ID"         -> InternalError,
```

2023-08-30 11:36 UTC, mattstephens-hmrc commented on app/v3/models/request/submitFinalDeclaration.scala
> +  def toNrsJson: JsValue = Json.obj("calculationId" -> calculationId.calculationId)
no need, "calculationId.calculationId" is already a string

2023-08-30 11:37 UTC, mattstephens-hmrc commented on app/v4/models/request/submitFinalDeclaration.scala
> +  def toNrsJson: JsValue = Json.obj("calculationId" -> calculationId.calculationId)
(no need, same as for v3)

2023-08-30 11:42 UTC, mattstephens-hmrc commented on test/v3/services/RetrieveCalculationServiceSpec.scala
>    private val taxYear       = "2019-20"
not needed in this case for a private val

2023-08-30 11:42 UTC, mattstephens-hmrc commented on test/v3/services/RetrieveCalculationServiceSpec.scala
>    private val calculationId = "someCalcId"
same

2023-08-30 11:44 UTC, mattstephens-hmrc commented on test/v3/services/RetrieveCalculationServiceSpec.scala
>    private val calculationId = "someCalcId"
same

2023-08-31 14:34 UTC, KobithasanVasantharajah approved these changes

2023-08-31 14:34 UTC, merged