[MTDSA-26988] submit final declatration CalculationType path parameter
hmrc/individual-calculations-api pull request #545
Opened 2024-10-23 14:19 UTC by juamalBlackman

2024-10-25 16:04 UTC, GazalNebHMRC requested changes

2024-10-28 10:48 UTC, Tateni93 commented on app/api/errors/IndividualCalculationsErrors.scala
> +      message = "The remote endpoint has indicated that the request cannot be completed as you are outside the amendment window.",
https://jira.tools.tax.service.gov.uk/browse/MTDSA-26988 - This is straight out of the ticket. I'll check anyway

2024-10-28 13:13 UTC, Tateni93 commented on app/api/errors/IndividualCalculationsErrors.scala
> +      message = "The remote endpoint has indicated that the request cannot be completed as you are outside the amendment window.",
Asked Sion to take a look. Will update on his response.

2024-10-28 13:28 UTC, Tateni93 commented on test/v7/submitFinalDeclaration/def1/Def1_SubmitFinalDeclarationRulesValidatorSpec.scala
> +class Def1_SubmitFinalDeclarationRulesValidatorSpec extends UnitSpec {
I disagree here, the Rules Validator is specific to determining whether a valid request satisfies business logic making it different from validating the format of path parameters and is its own object therefore a separate spec is required.

2024-10-28 13:42 UTC, sion-docs commented on app/api/errors/IndividualCalculationsErrors.scala
> +      message = "The remote endpoint has indicated that the request cannot be completed as you are outside the amendment window.",
See the first point here - https://confluence.tools.tax.service.gov.uk/display/MTE/How+to+write+error+messages. I suggest changing to "The request cannot be completed as you are outside the amendment window"

2024-10-28 14:06 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/main/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2024-10-28 16:02 UTC, EdCope commented on app/v7/submitFinalDeclaration/SubmitFinalDeclarationValidatorFactory.scala
> +      case Def1 => new Def1_SubmitFinalDeclarationValidator(nino, taxYear, calculationId, calculationType)
The import for `Def1` is missing here

2024-10-28 16:03 UTC, EdCope commented on resources/public/api/conf/7.0/common/errors.yaml
> +    ruleOutisdeAmendmentWindow:
There is a typo here `...OutisdeAme...`

2024-10-29 09:43 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/main/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2024-10-29 10:53 UTC, EdCope commented on resources/public/api/conf/7.0/submit_final_declaration.yaml
> +              $ref: ./common/errors.yaml#/components/examples/ruleOutisdeAmendmentWindow
Use the same typo correction here

2024-10-29 10:57 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/main/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2024-10-29 13:33 UTC, Tateni93 commented on app/v7/submitFinalDeclaration/def1/Def1_SubmitFinalDeclarationRulesValidator.scala
> +        case `confirm-amendment` if request.taxYear.year < 2026 => Invalid(Seq(RuleSubmissionFailedError))
I'm not sure what is meant here? Are we saying the current message attached to this error needs to be overridden for this case?

2024-10-29 13:36 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/main/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2024-10-29 13:55 UTC, GazalNebHMRC commented on app/api/errors/IndividualCalculationsErrors.scala
> +      message = "The remote endpoint has indicated that the request cannot be completed as you are outside the amendment window.",
Can you please update the error message to ""The request cannot be completed as you are outside the amendment window" as indicated above? Also, @sion-docs Can you please update the business spec [API#2082(1780) - Submit a Self Assessment Final Declaration and Confirm Amendment (TYS)](https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=955810017) with the new error message for RULE_OUTSIDE_AMENDMENT_WINDOW as well?

2024-10-29 14:34 UTC, GazalNebHMRC commented on app/v7/submitFinalDeclaration/def1/Def1_SubmitFinalDeclarationRulesValidator.scala
> +        case `confirm-amendment` if request.taxYear.year < 2026 => Invalid(Seq(RuleSubmissionFailedError))
After confirmation with our software architect Fatih, it seems no further change is required for this, thanks

2024-10-29 14:49 UTC, Tateni93 commented on test/v7/submitFinalDeclaration/SubmitFinalDeclarationServiceSpec.scala
> +        ("INVALID_TAX_YEAR", TaxYearFormatError),
INVALID_CALCULATION_ID  is on Line 80 but I have added Calculation Type and Outside Amendment Window tests

2024-10-29 16:15 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/main/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2024-10-29 16:27 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/main/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2024-10-29 16:30 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/main/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2024-10-29 16:40 UTC, EdCope commented on app/api/errors/IndividualCalculationsErrors.scala
> +      message = "You are outside the amendment window",
This comment was on before you rebased, `The request cannot be completed as you are outside the amendment window`

2024-10-29 16:46 UTC, Tateni93 commented on app/api/errors/IndividualCalculationsErrors.scala
> +      message = "You are outside the amendment window",
Sion messaged me again this morning to say that the message should be You are Outside the amendment window. @sion-docs is this still the correct message?

2024-10-29 16:54 UTC, Tateni93 commented on app/v7/submitFinalDeclaration/model/request/domain/CalculationType.scala
I can't see that path under common folder there is a shared.models.domain. Do you mean to move it there?

2024-10-29 16:59 UTC, EdCope commented on app/api/errors/IndividualCalculationsErrors.scala
> +      message = "The provided calculation type is not valid.",
Please remove the full stop for the message

2024-10-29 17:01 UTC, EdCope commented on resources/public/api/conf/7.0/common/errors.yaml
> +        message: You are outside the amendment window
Match to above when we have received confirmation for your question:

https://github.com/hmrc/individual-calculations-api/pull/545/files#r1821198876

2024-10-29 17:33 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/main/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2024-10-30 09:41 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/main/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2024-10-30 09:47 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/main/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2024-10-30 09:51 UTC, sion-docs submitted a review, later dismissed

2024-10-30 09:51 UTC, sion-docs commented on app/api/errors/IndividualCalculationsErrors.scala
> +      message = "You are outside the amendment window",
Correct, it should be simply "You are outside the amendment window". This is for consistency with other error messages, and 'The request cannot be completed' is redundant as they are receiving an error message.

2024-10-30 09:56 UTC, sion-docs commented on app/api/errors/IndividualCalculationsErrors.scala
> +      message = "The remote endpoint has indicated that the request cannot be completed as you are outside the amendment window.",
Revise to 'You are outside the amendment window'. This is for consistency with other error messages, and 'The request cannot be completed' is redundant as they are receiving an error message.

2024-10-30 11:01 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/main/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2024-10-30 11:22 UTC, GazalNebHMRC approved these changes

2024-10-30 12:55 UTC, closed without merging